### ISSUE TITLE
`--pfer-api` fails when the API is not reachable

### ISSUE THREAD

**Issue by LasaleFamine** [contactlab/saray#66]
If the API is not reachable (like an API behind a proxy...) Saray become unreachable too.

**Comment by pferretti** [comment]
I'm trying to reproduce the bug so I'm explaining what I've discovered by now with @LasaleFamine.
It seems that the failure happens when the address configured as endpoint is unreachable and the endpoint itself doesn't respond immediately but it leaves the http request pending. In this way, Saray also remains pending and the failure occurs.

Probably it would be a good idea to let Saray handle a timeout and respond with an HTTP 408 if a timeout occurs.
